### ISSUE TITLE
Deselect All does not deselect all rules

### ISSUE THREAD

**Issue by zemb** [OpenSCAP/scap-workbench#23] opened 2015-06-29 23:54 UTC
During tailoring, the rules that were checked before tailoring stay intact when I click Deselect All.

Only those that I check first, get deselected this way. Is this the way it is supposed to work?

scap-workbench 1.0.2, compiled with Qt 4.8.5, using openscap 1.2.4

**Comment by ybznek** [comment] 2016-08-25 11:50
@zemb I cannot reproduce your issue and I don't see any changes in the code what could fix your problem after you've filled it.

I can see, that Groups are not deselected during "deselect all", but I am not sure if it is a bug.

Can you still reproduce it?

**Comment by yuumasato** [comment] 2017-05-11 14:42
Fixed by #113

**Closed by yuumasato** 2017-05-11 14:42 UTC
