### ISSUE TITLE
 remote port number not fully configurable

### ISSUE THREAD

**Issue by zemb** [OpenSCAP/scap-workbench#19] opened 2015-05-06 15:54 UTC
Description of problem:
scap-workbench tries to connect to port 22 when remote scanning through SSH even when a non-standard port is specified. Maybe this is the bug that you (Martin) told me about, I do not know, now the scan starts correctly, but some operations AFTER the scan use the port 22.

Version-Release number of selected component (if applicable):
scap-workbench-1.0.3-2.el6

How reproducible:
Always

Steps to Reproduce:
1. choose any profile, e.g. the STIG profile
2. do tailoring so that it does not take so long if you like to
3. specify "remote machine (over ssh) and change port from 22 to something else, e.g. 1222 and start the scan
4. wait for results or for an error window to rise

Actual results:
errors

Expected results:
no errors like those below (port 22: Network is unreachable)

Additional info:
17:01:48 | info     | Establishing connecting to remote target...
17:01:52 | info     | Connection established.
17:01:53 | info     | Querying capabilities on remote machine...
17:01:53 | info     | Copying input data to remote target...
17:01:53 | info     | Starting the remote process...
17:01:53 | info     | Processing on the remote machine...
QObject: Cannot create children for a parent that is in a different thread.
(Parent is OscapScannerRemoteSsh(0x2afd9e0), parent's thread is QThread(0xb3a7e0), current thread is QThread(0x1d51f50)
17:02:32 | warning  | Failed to copy back XCCDF results. You will not be able to save this data! Diagnostic info: Starting process 'Remote command 'cat /tmp/tmp.bjsg0OrOVR' on machine 'root@localhost''
Starting process 'Remote command 'cat /tmp/tmp.bjsg0OrOVR' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

QObject: Cannot create children for a parent that is in a different thread.
(Parent is OscapScannerRemoteSsh(0x2afd9e0), parent's thread is QThread(0xb3a7e0), current thread is QThread(0x1d51f50)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is OscapScannerRemoteSsh(0x2afd9e0), parent's thread is QThread(0xb3a7e0), current thread is QThread(0x1d51f50)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is OscapScannerRemoteSsh(0x2afd9e0), parent's thread is QThread(0xb3a7e0), current thread is QThread(0x1d51f50)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is OscapScannerRemoteSsh(0x2afd9e0), parent's thread is QThread(0xb3a7e0), current thread is QThread(0x1d51f50)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is OscapScannerRemoteSsh(0x2afd9e0), parent's thread is QThread(0xb3a7e0), current thread is QThread(0x1d51f50)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is OscapScannerRemoteSsh(0x2afd9e0), parent's thread is QThread(0xb3a7e0), current thread is QThread(0x1d51f50)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is OscapScannerRemoteSsh(0x2afd9e0), parent's thread is QThread(0xb3a7e0), current thread is QThread(0x1d51f50)
17:02:32 | warning  | Failed to copy back XCCDF report (HTML). You will not be able to save this data! Diagnostic info: Starting process 'Remote command 'cat /tmp/tmp.GQDRQM2wLd' on machine 'root@localhost''
Starting process 'Remote command 'cat /tmp/tmp.GQDRQM2wLd' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

17:02:32 | warning  | Failed to copy back Result DataStream (ARF). You will not be able to save this data! Diagnostic info: Starting process 'Remote command 'cat /tmp/tmp.fps0csUPq7' on machine 'root@localhost''
Starting process 'Remote command 'cat /tmp/tmp.fps0csUPq7' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

17:02:34 | info     | Cleaning up...
17:02:34 | warning  | Failed to remove remote file input file. Diagnostic info: Starting process 'Remote command 'rm /tmp/tmp.GU7op73Luc' on machine 'root@localhost''
Starting process 'Remote command 'rm /tmp/tmp.GU7op73Luc' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

17:02:34 | warning  | Failed to remove remote file tailoring file. Diagnostic info: Starting process 'Remote command 'rm /tmp/tmp.dNCSLdlgkB' on machine 'root@localhost''
Starting process 'Remote command 'rm /tmp/tmp.dNCSLdlgkB' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

17:02:34 | warning  | Failed to remove remote file XCCDF result file. Diagnostic info: Starting process 'Remote command 'rm /tmp/tmp.bjsg0OrOVR' on machine 'root@localhost''
Starting process 'Remote command 'rm /tmp/tmp.bjsg0OrOVR' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

17:02:34 | warning  | Failed to remove remote file XCCDF report file. Diagnostic info: Starting process 'Remote command 'rm /tmp/tmp.GQDRQM2wLd' on machine 'root@localhost''
Starting process 'Remote command 'rm /tmp/tmp.GQDRQM2wLd' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

17:02:34 | warning  | Failed to remove remote file Result DataStream file. Diagnostic info: Starting process 'Remote command 'rm /tmp/tmp.fps0csUPq7' on machine 'root@localhost''
Starting process 'Remote command 'rm /tmp/tmp.fps0csUPq7' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

17:02:34 | warning  | Failed to remove remote directory Temporary Working Directory. Diagnostic info: Starting process 'Remote command 'rm -rf /tmp/tmp.SRdw49eBVD' on machine 'root@localhost''
Starting process 'Remote command 'rm -rf /tmp/tmp.SRdw49eBVD' on machine 'root@localhost''
stdout:
===============================

stderr:
===============================
ssh: connect to host localhost port 22: Network is unreachable

17:02:34 | info     | Processing has been finished!

**Comment by mpreisler** [comment] 2015-06-17 12:08
Hi, I have tested this with v1-0 and I cannot reproduce the issue. As such I am closing it.

Can you verify that you have this issue with latest v1-0? If so, please reopen.

**Comment by zemb** [comment] 2015-06-24 16:34
Thank you for checking it out.

I can reproduce it with the abovementioned (packaged) version. I have tried with current v1-0 after compilation and it displays this instead:

When scanning remote, SSH running on 1222:
Can't connect to remote machine! Exception was: There was a problem with SshConnection! Failed to create SSH master socket! Diagnostic info: Starting process 'setsid -w ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=/tmp/tmp.90XOmv2qBZ/ssh_socket -p 1222 localhost' Starting process 'setsid -w ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=/tmp/tmp.90XOmv2qBZ/ssh_socket -p 1222 localhost' stdout: =============================== stderr: =============================== execvp: No such file or directory

**Comment by mpreisler** [comment] 2015-06-24 16:38
Which distro are you testing on?

**Comment by zemb** [comment] 2015-06-24 16:38
RHEL-6

**Comment by mpreisler** [comment] 2016-08-09 18:35
This has been fixed for a long time...

**Closed by mpreisler** 2016-08-09 18:35 UTC
Labels: invalid
