### ISSUE TITLE
Unexpected crash in opening SCAP contents.

### ISSUE THREAD

**Issue by raphaell** [OpenSCAP/scap-workbench#129] opened 2017-06-16 14:55 UTC
Hi~

I encountered problem when using SCAP-Workbench-1.1.4
When first popup, i didn't not choose drop menu in "load content". I chose  "other SCAP content" to open SSG by myself.
I took the one from SSG folder. and then it unexpected crashed.
Is it bug or not? when using it from linux it okay. I want to eager to resolve a problem. 
How do i do ?

**Comment by yuumasato** [comment] 2017-06-19 07:44
Hello, @raphaell 
It is not clear to me which version is crashing. Is it the binary for Windows or Mac?

**Comment by raphaell** [comment] 2017-06-21 08:42
Hello, @yuumasato 
hmm. It's bin for Windows. I have installed it
after I got MSI from https://www.open-scap.org/download/ 

SCAP-Workbench info: 1.1.4, compiled with Qt 4.8.6 usning OpenSCAP 1.3.0

**Comment by yuumasato** [comment] 2017-06-21 08:50
There is a new version out, 1.1.5. Could you try with that?
If it is still crashing, could you say which data stream you are loading and its version? 
If compiled from source specify the head commit.

Thank you.

**Comment by raphaell** [comment] 2017-06-21 09:30
@yuumasato 
I installed new one. but I have met a same situation. (Crashed)
when loading DS from SSG folder which is built when installing SCP-workbench(1.1.5) 
all of DS are broken in my desktop (Windows 10  pro version : 10.0.14393)
Is it QT bug? I'm not sure but I think it's okay on linux when testing.
Could you resolve it? 

Thank you.

**Comment by WesleyCeraso** [comment] 2017-06-22 16:12
Hi @raphaell,

Was your environment fresh before the instalation of the workbench or did you have older versions? Can you check if the scap-workbench.exe is loading the libopenscap-8.dll that goes along with it?

**Comment by raphaell** [comment] 2017-06-23 11:47
Hi @WesleyCeraso 

Sure. I used old one before but I removed it (Windows appwiz.cpl) before installing new one.
It's okay after selecting one at first pop-up shown not select "Other SCAP content"
I'm not sure but I think there is no problem loading libopenscap-8.dll. 
How to trace loading it by scap-workbench.exe
let me know that. 
I will check it.

Thank you.

**Comment by WesleyCeraso** [comment] 2017-06-23 13:59
@raphaell 
If it were libopenscap-8.dll fault, it would crash always, even when you do not choose "Other SCAP content".
That's the only way I could reproduce it so far :/

**Comment by WesleyCeraso** [comment] 2017-06-23 14:13
@raphaell 
Just to be sure, can you replace the lib with the one attached (extract it) and tell us if it works?
[libopenscap-8.zip](https://github.com/OpenSCAP/scap-workbench/files/1098024/libopenscap-8.zip)

**Comment by raphaell** [comment] 2017-06-23 14:29
@WesleyCeraso 
Of course. I replaced DLL to install dir but I'v met same situation. 
xccdf_session_load() is trigger when I tracked this issue.

**Comment by WesleyCeraso** [comment] 2017-06-29 16:24
@raphaell 
Man, you have no ideia how hard it was to find the root cause of this bug. If you want to see the fix: OpenSCAP/openscap/pull/770

I`m not sure when there will be a new release with this fix because it's not in scap-workbench, but openscap itself. However, if you need to use it before, you can use this dll:
[libopenscap-8.zip](https://github.com/OpenSCAP/scap-workbench/files/1112762/libopenscap-8.zip)

Thanks for the report

**Comment by raphaell** [comment] 2017-07-03 04:23
@WesleyCeraso 
Good jobs 👍 . Thank you for your patch.

**Comment by jan-cerny** [comment] 2017-07-03 07:04
Fixed in https://github.com/OpenSCAP/openscap/pull/770

**Closed by jan-cerny** 2017-07-03 07:04 UTC
