### ISSUE TITLE
OpenScap Workbench isn't working on Linux Mint.

### ISSUE THREAD

**Issue by salmankhwaja** [OpenSCAP/scap-workbench#235] opened 2019-10-29 09:28 UTC
Hi, 
I installed OpenScap and OpenScap workbench using the following commands. 

$ sudo apt-get install libopenscap8
$ sudo apt-get install scap-workbench

Now I want OpenScap-Security-Guides to scan the system. Once my Workbench is up, it displays nothing, but a small bar. (attaching a snapshot). I made sure, my internet is working, but that's about it.

I may be expereicning proxy issues in my office. I have taken the download rights, but still it's not working. Any ideas how can I trouble shoot it. ? 

![Screenshot at 2019-10-29 14-28-38](https://user-images.githubusercontent.com/702831/67754537-6b8d5000-fa58-11e9-8942-ceb4b5888d7a.png)

**Comment by jan-cerny** [comment] 2019-10-30 09:12
I'm not familiar with Linux Mint. AFAIK there is no Linux Mint content in scap-security-guide. If the scap-security-guide package is available, it probably contains only Debian or Ubuntu. 

Try to download any content, eg. from the latest upstream release https://github.com/ComplianceAsCode/content/releases/download/v0.1.46/scap-security-guide-0.1.46.zip and open any file using the "File - Open" menu. That can help you to troubleshoot if the problem is in scap-security-guide on your installation or if it is really a problem with scap-workbench.

Connectivity issues should not be related, because SCAP Workbench doesn't connect or download anything unless you tick "Fetch remote resources" button.

**Comment by stringz** [comment] 2019-11-05 10:08
Thanks. Is there any place where OSCAP performs it's logging. May be I could have a look at OSCAP Workbench Logs and OSCAP logs.

**Comment by cipherboy** [comment] 2021-04-26 17:27
Duplicate of #252. Please see reason there. You need to load content first.

**Closed by cipherboy** 2021-04-26 17:27 UTC
