### ISSUE TITLE
Windows 8.1

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/scap-workbench#54] opened 2015-12-02 09:25 UTC
In OS Windows 8.1 my tested user downloaded and installed SCAP Workbench, but the SW didn't run. It just never opened. Or better said, it seemed to me that it opened for one millisecond but immediately it disappeared. But not sure with that. I looked for running SWs on my computer and SCAP Workbench wasn't between them even after various tries to start it.

**Comment by ybznek** [comment] 2015-12-04 09:26
I expect, that you don't have any output from command line?

**Comment by lhorakov** [comment] 2015-12-04 10:46
It wasn't done by command line. :) So nope. Feel free to ask me any other questions, even I can make a video of my home computer of this process if it would help you.

**Comment by jan-cerny** [comment] 2015-12-04 11:36
@lhorakov I think the video would not be helpful, because as you said in your first comment, we would see nothing on the video :-) However, if you have the SCAP Workbench still installed on your computer, it will be cool to run the SCAP Workbench from the command line interface and copy paste the output here.

**Comment by mpreisler** [comment] 2015-12-04 12:39
The installer never opened or workbench never opened?

+1 for running it from command line, maybe it's writing some error out.

**Comment by lhorakov** [comment] 2015-12-08 08:33
Installer opened, you could easily install it and the installation process also finished. Then trying to start the program failed. Nothing happened.

**Comment by mpreisler** [comment] 2015-12-08 14:25
Ok, thanks, I will check this out.

**Comment by mpreisler** [comment] 2016-07-12 17:56
I cannot reproduce this on any Windows I tried - Window 7, 8.1, 10. Can you reproduce this, @ybznek ? If not, I suggest we close this bug.

**Comment by ybznek** [comment] 2016-07-13 08:14
I have clean images of Win7, Win8 and new (currently not released) version started correctly. On win10 it started correctly too, but the image wasn't clean.

Previous release hasn't contained less dlls, so I don't know any reason why it could have problems.

I will close this issue after new release.

**Comment by ybznek** [comment] 2016-07-13 13:34
I wasn't able to reproduce it on clean Win7, Win8.1, Win10. We are not able to reproduce it, so I think it wasn't caused by workbench.

**Closed by ybznek** 2016-07-13 13:34 UTC
