### ISSUE TITLE
User manual does not work on Fedora 22

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/scap-workbench#42] opened 2015-08-27 08:15 UTC
I have SCAP Workbench 1.1.0 on Fedora 22. After clicking on Help --> User Manual, nothing happens.

**Comment by mpreisler** [comment] 2015-08-28 22:44
Thanks for the report!

Can you give me your configure flags? I need to know how you built SCAP Workbench. I am especially interested in CMAKE_INSTALL_PREFIX.

Is there anything in `stderr` or `stdout`?

**Comment by jan-cerny** [comment] 2015-08-31 06:14
I did not build it from source, i have installed Workbench using `sudo dnf install scap-workbench`.

**Comment by mpreisler** [comment] 2015-08-31 15:00
Ah, OK. I assumed since you reported to the upstream bug tracker that you built it yourself.

> Is there anything in stderr or stdout?

^

**Comment by jan-cerny** [comment] 2015-08-31 18:56
In stderr or stdout of dnf? Everything was OK about the installation, so I did not keep dnf's output..

**Comment by mpreisler** [comment] 2015-09-01 09:20
No, I want `stdout` and `stderr` of SCAP Workbench when it fails to open the manual.

**Comment by mpreisler** [comment] 2015-09-02 12:24
I went ahead and have reproduced this myself. It's a bug that has been solved in 50b319338479d44a41c5369faa25c311b61dafc2 but there has been no upstream release since then. This will be fixed when 1.1.1 is released which should be later this month.

This is also a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1218813

**Closed by mpreisler** 2015-09-02 12:24 UTC
Labels: bug
